### ISSUE TITLE
Which VS version to use

### ISSUE THREAD

**Issue by gsantopaolo** [Microsoft/AppConsult-WinAppsModernizationWorkshop#14]
Hi there
    Which VS version is needed to open exercises' solutions?
 I'm asking because I still don't have 19 on my prod machine (the one i'll bring at Build), mostly working with VS Code and Python nowadays, and looking at the [Exercise 1 sln file](https://github.com/Microsoft/AppConsult-WinAppsModernizationWorkshop/blob/master/Exercise1/01-Start/ContosoExpenses.sln) it seems was created with an early VS19 version not even reported in the [Visual Studio build numbers and release dates](https://docs.microsoft.com/en-us/visualstudio/install/visual-studio-build-numbers-and-release-dates?view=vs-2019).
My plan is to install VS19 16.0.1 Release in the next days, would it be good to run all the Exercises?

On a side note: i received the Post Day training confirmation from eventcore, the same also attendee received (i suppose), checked out the Build registration site for the Post event, and i didn't find any information if attendee has to bring their own laptop (plus all the software needed eg VS 19 version) or if there will be a pc for any of the attendee

thank you
/gp

@qmatteoq this is obviously a question but i don't have rights to add the appropriate label

**Comment by qmatteoq** [comment]
Hello Gian Paolo,
all the exercises require Visual Studio 2019, since it's the version to use for .NET Core 3.0.
All the exercises have been opened and compiled with the official RTM version, so I'm not sure why you're seeing a weird version number.

However, the solution / project file format didn't change between Visual Studio 2017 and 2019. As such, you should be able to open the solution with every edition of VS2017 and VS2019. However, the latter is suggested because it has a much better support to .NET Core 3.0.
